# Generated by Django 3.2.5 on 2021-08-02 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchEngine', '0003_passreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=127)),
                ('time', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('record', models.CharField(max_length=255)),
                ('fuzzy', models.BooleanField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
